services:
  backend:
    build:
      context: ./Backend
    container_name: translation-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: translation-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

